use_frameworks!

platform :ios, '8.0'

target 'XUAlertView_Example' do
  pod 'XUAlertView', :path => '../'

  target 'XUAlertView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
